import Head from 'next/head'
import {AiFillHome} from 'react-icons/ai';
import {AiFillGithub} from 'react-icons/ai';
import { AiFillLinkedin} from 'react-icons/ai';

export default function Home() {
  return (
    <>
      <Head>
        <title>Vanessa Marie Tan Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" font-body px-10 bg-palette-beige min-h-screen">
        <section>
          <nav className="pt-5 mb-5 flex justify-between flex-wrap gap-y-2.5">
            <ul className="flex items-center space-x-4">
              <li>
                <a href="#" className="text-2xl hover:text-palette-blue-700"><AiFillHome /></a>
              </li>
              <li>
                <a href="#" className=" hover:border-b-2 hover:border-palette-blue-700 font-bold py-2">About Me</a>
              </li>
              <li>
                <a href="#" className=" hover:border-b-2 hover:border-palette-blue-700 font-bold py-2 ">Portfolio</a>
              </li>
              <li>
                <a href="#" className=" hover:border-b-2 hover:border-palette-blue-700 font-bold py-2 ">Contact</a>
              </li>
            </ul>
            <a href="#" className=" bg-palette-blue-500 hover:bg-palette-blue-700 px-4 py-2 rounded-md text-white border-none">Résumé</a>
          </nav>
        </section>

        <section name="about-me" className=' text-center pt-20 max-w-screen-md  mx-auto'>
          <h2 className=" text-5xl my-2 font-heading text-palette-pink">Vanessa Marie Tan</h2>
          <h3 className=" text-2xl mb-2 font-heading text-palette-pink">Developer and CPA.</h3>
          <div className='flex justify-center gap-x-10 gap-y-2.5 text-3xl mb-10 text-palette-blue-500'>
            <a href="#"><AiFillGithub /></a>
            <a href="#"><AiFillLinkedin /></a>
          </div>
          <p className=' text-gray-700 font-bold'>
            Passionate and diligent computer science student and a Certified Public Accountant with 1 year experience at a large accounting firm. Seeking to use my software engineering and finance skills to implement innovative solutions and expand my knowledge of emerging technologies.
          </p>
        </section>
      </main>
    </>
  )
}
